config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  # /:path
  resources :pages, path: '', only: [] do
    collection do
      get 'pricing'
      get 'about'
      get 'newsletter'
      get 'love'
      get 'feedback'
      get 'features'

      # For analytics
      post 'track_social'
      post 'track_time'
      post 'submit_feedback'
    end
  end

  scope module: :admin do
    # /metrics/:path
    resources :metrics, only: :index do
      collection do
        get 'newsletter'
        get 'traffic'
        get 'social'
      end
    end

    # /charts/:path
    resources :charts, only: [] do
      collection do
        get 'subscription_ratio'
        get 'subscription_by_date'
        get 'landing_page_feedback'

        get 'social_share_ratio'
        get 'social_share_by_date'

        get 'referrers_ratio'
        get 'referrers_by_date'
        get 'average_time_spent_per_page'
        get 'number_of_visits_per_page'

        get 'newsletter_subscription_by_date'
        get 'unsubscription_by_newsletter'
        get 'unsubscription_reason'
      end
    end

    # /newsletters/:path
    resources :newsletters, only: %i[index create new show] do
      collection do
        get 'subscribers'
        get 'unsubscribe'

        post 'subscribe'
        post 'unsubscribe', to: 'newsletters#post_unsubscribe'
      end
    end
  end

  namespace :admin do
    resources :dashboard, only: :index

    resources :categories, only: %i[index create update destroy]
    resources :skills, only: %i[index create update destroy]
  end

  resources :categories, only: :index
  resources :skills, only: :index

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # /users/:path
  resources :users, only: %i[index show] do
    member do
      get 'timeline'
    end
  end

  # /settings/:path
  scope module: :users do
    namespace :settings do
      resource :profile, only: %i[show update] do
        delete 'remove_avatar'
      end

      resource :account, only: :show do
        delete 'disconnect_omniauth'
        put 'reset_password'
      end

      resource :billing, only: %i[show update]

      resource :personality, only: %i[show update]

      resource :skills, only: %i[show create destroy]

      resource :emails, only: :show do
        post 'subscribe'
        post 'unsubscribe'
      end
    end
  end

  # /projects/:path
  resources :projects do
    get 'explore', on: :collection

    # TODO: change the name?
    member do
      get 'count'
      patch 'change_status'
    end

    scope module: :projects do
      scope module: :teams do
        resources :teams, except: %i[index]

        resources :manage, only: %i[index create] do
          collection do
            get 'suggest'
            get 'manage_data'
            post 'recompute_data'
            delete 'remove_user'
          end
        end
      end

      shallow do
        scope module: :appeals do
          resources :invitations, only: %i[index create destroy] do
            post 'accept', on: :member
          end

          resources :applications, only: %i[index create destroy] do
            post 'accept', on: :member
          end
        end
      end

      resources :tasks, except: %i[index show] do
        collection do
          get 'data'
        end

        member do
          patch 'set_percentage'
          patch 'assign_self'
        end
      end
    end
  end

  # /notifications/:path
  resources :notifications, only: %i[index destroy] do
    member do
      patch 'read'
      patch 'unread'
    end

    patch 'read_all', on: :collection
  end

  authenticated :user do
    root to: 'projects#index', as: :authenticated_root
  end

  root to: 'pages#home'
end

app/models/team.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: teams
#
#  id         :bigint           not null, primary key
#  name       :string           default(""), not null
#  team_size  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :bigint           not null
#
# Indexes
#
#  index_teams_on_name_and_project_id  (name,project_id) UNIQUE
#  index_teams_on_project_id           (project_id)
#
# Foreign Keys
#
#  fk_rails_...  (project_id => projects.id)
#

class Team < ApplicationRecord
  belongs_to :project

  # Join table
  has_many :collaborations, dependent: :destroy
  has_many :users, through: :collaborations, before_add: :check_users_limit,
                   after_add: :send_notification,
                   after_remove: :unassign_tasks
  has_many :team_skills, dependent: :destroy
  has_many :skills, through: :team_skills

  validates :name,
            presence: true,
            uniqueness: { scope: :project_id, message: 'already exist' }
  validates :team_size,
            presence: true,
            numericality: { greater_than_or_equal_to: 1 }

  after_destroy_commit :destroy_notifications

  private

  def check_users_limit(_)
    return project.check_users_limit unless users.size > team_size

    errors[:base] << 'Team Size is smaller than total members'
  end

  def send_notification(user)
    return if name == 'Unassigned'

    SendNotificationJob.perform_later(
      [user],
      { key: 'team', notifiable: project, notifier: self }
    )
  end

  def unassign_tasks(user)
    return if user.in_project?(project)

    tasks = user.tasks.where(project: project)

    tasks.each do |task|
      task.users.delete(user)
    end
  end

  def destroy_notifications
    Notification.delete_by(notifier: self)
  end
end

app/controllers/projects/appeals/applications_controller.rb
# frozen_string_literal: true

class Projects::Appeals::ApplicationsController < Projects::Appeals::BaseController
  before_action :set_application, only: %i[accept destroy]

  def index
    project = Project.find(params[:project_id])
    authorize! project, with: Appeal::ApplicationPolicy

    render json: { applications: Appeal.application.list_in_project(project) }
  end

  def create
    @application = Appeal.new(user: current_user, project_id: params[:project_id], type: 'application')

    authorize! @application, with: Appeal::ApplicationPolicy
    return application_fail unless @application.save

    flash[:toast_success] = 'Application sent'
    render js: 'location.reload();'
  end

  def accept
    @application.project.unassigned_team.users << @application.user

    msg = @application.project.errors.full_messages
    return application_fail(msg) unless msg.blank? && @application.delete

    @application.send_resolve_notification('accept')
    head :ok
  end

  def destroy
    return application_fail unless @application.delete

    @application.send_resolve_notification('decline', current_user == @application.user)

    # TODO: should return JSON only, otherwise the Table will redirect
    flash[:toast_success] = 'Application deleted'
    render js: 'location.reload();'
  end

  private

  def application_fail(msg = @application.errors.full_messages)
    render json: { message: msg }, status: :unprocessable_entity
  end

  def set_application
    @application = Appeal.application.find(params[:id])
    authorize! @application, with: Appeal::ApplicationPolicy
  end
end

app/controllers/projects/appeals/base_controller.rb
# frozen_string_literal: true

class Projects::Appeals::BaseController < ApplicationController
  rescue_from ActionPolicy::Unauthorized do
    head :forbidden
  end
end

app/controllers/projects/appeals/invitations_controller.rb
# frozen_string_literal: true

class Projects::Appeals::InvitationsController < Projects::Appeals::BaseController
  before_action :set_invitation, only: %i[accept destroy]

  def index
    project = Project.find(params[:project_id])
    authorize! project, with: Appeal::InvitationPolicy

    render json: { invitations: Appeal.invitation.list_in_project(project) }
  end

  def create
    @invitation = Appeal.new(user: User.find_by(email: params[:email]),
                             project_id: params[:project_id],
                             type: 'invitation')

    authorize! @invitation, with: Appeal::InvitationPolicy
    return invitation_fail unless @invitation.save

    render json: { invitation: @invitation }
  end

  def accept
    @invitation.project.unassigned_team.users << @invitation.user

    msg = @invitation.project.errors.full_messages
    return invitation_fail(msg) unless msg.blank? && @invitation.delete

    @invitation.send_resolve_notification('accept')
    render js: 'location.reload();'
  end

  def destroy
    return invitation_fail unless @invitation.delete

    @invitation.send_resolve_notification('decline', current_user == @invitation.user)

    # TODO: should return JSON only, otherwise the Table will redirect
    flash[:toast_success] = 'Invitation deleted'
    render js: 'location.reload();'
  end

  private

  def invitation_fail(msg = @invitation.errors.full_messages)
    render json: { message: msg }, status: :unprocessable_entity
  end

  def set_invitation
    @invitation = Appeal.invitation.find(params[:id])
    authorize! @invitation, with: Appeal::InvitationPolicy
  end
end

app/controllers/projects/tasks_controller.rb
# frozen_string_literal: true

class Projects::TasksController < ApplicationController
  before_action :set_task,
                only: %i[edit update set_percentage assign_self destroy]
  before_action :set_project,
                except: %i[update destroy assign_self set_percentage]
  before_action :set_skills, only: %i[new edit]

  layout 'project'

  # GET /tasks/new
  def new
    @task = Task.new(project: @project)
    authorize! @project, to: :create_task?
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  def create
    authorize! @project, to: :create_task?
    @task = @project.tasks.build(create_params)

    if @task.save
      @task.skill_ids = params.dig(:task, :skill_ids)
      @task.user_ids =  params.dig(:task, :user_ids)
      task_success('Task created')
    else
      task_fail
    end
  end

  # PATCH/PUT /tasks/1
  def update
    @task.update(edit_params) ? task_success('Task updated') : task_fail
  end

  def assign_self
    return task_fail('Task is already Assigned') if @task.users.present?

    @task.users << current_user
    @task.send_picked_up_notification
    head :ok
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    head :ok
  end

  def data
    extend AvatarHelper

    return render_404 unless request.xhr? && valid_data_type?

    render json: {
      data: TaskBlueprint.render_as_json(
        authorized_scope(@project.tasks, as: @type).includes(users: [{ avatar_attachment: :blob }])
      )
    }
  end

  def set_percentage
    @task.update(edit_params) ? head(:ok) : task_fail
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_skills
    @skills = @project.category.skills.map { |s| [s.name, s.id] }

    team = current_user.teams.find_by(project: @project)
    @assignees = authorized_scope(
      @project.users,
      as: :assignee,
      scope_options: { team_id: team&.id, project: @project }
    )
  end

  def set_task
    @task = Task.find(params[:id])
    authorize! @task
  end

  def create_params
    params.require(:task)
          .except(:skill_ids, :user_ids)
          .permit(:name, :description, :priority)
          .merge(user: current_user)
  end

  def edit_params
    params.require(:task).permit(:description, :name,
                                 :percentage, :priority,
                                 skill_ids: [], user_ids: [])
  end

  def task_fail(message = @task.errors.full_messages)
    render json: { message: message }, status: :unprocessable_entity
  end

  def task_success(message)
    flash[:toast_success] = message
    render js: "window.location = '#{project_path(@task.project)}'"
  end

  def valid_data_type?
    authorize! @project, to: :count?

    @type = params[:type]&.to_sym
    %i[assigned unassigned active completed].include?(@type)
  end
end

app/controllers/projects/teams/base_controller.rb
# frozen_string_literal: true

class Projects::Teams::BaseController < ApplicationController
  layout 'project'

  private

  def set_team
    @team = Team.find(params[:id])
    authorize! @team
  end

  def set_skills
    @skills = Skill.where(category: @project.category)
                   .collect { |s| [s.name, s.id] }
  end

  def set_project
    @project = Project.find(params[:project_id])
    authorize! @project, to: :manage?
  end

  def team_success(message)
    flash[:toast_success] = message
    render js: "window.location = '#{project_manage_index_path(@project)}'"
  end

  def team_fail(message = @team.errors.full_messages)
    render json: { message: message }, status: :unprocessable_entity
  end
end

app/controllers/projects/teams/teams_controller.rb
# frozen_string_literal: true

class Projects::Teams::TeamsController < Projects::Teams::BaseController
  before_action :set_team, only: %i[edit show update destroy]
  before_action :set_project, except: %i[show]
  before_action :set_skills, only: %i[new edit]
  skip_before_action :authenticate_user!, only: %i[show]

  # GET /teams/new
  def new; end

  # GET /teams/1/edit
  def edit; end

  def show
    extend AvatarHelper

    return render_404 unless request.xhr?

    render json: { member: @team.users, skill: @team.skills&.select(:id, :name),
                   team: @team, images: get_avatars(@team.users.pluck('id')) }
  end

  # POST /teams
  def create
    @team = @project.teams.build(create_params)

    if @team.save
      @team.skill_ids = params[:team][:skill_ids]
      team_success('Team was successfully created')
    else
      team_fail
    end
  end

  # PATCH/PUT /teams/1
  def update
    @team.update(edit_params) ? team_success('Team Saved') : team_fail
  end

  # DELETE /teams/1
  def destroy
    @project.unassigned_team.users << @team.users
    @team.destroy
    head :ok
  end

  private

  def create_params
    params.require(:team).except(:skill_ids)
          .permit(:team_size, :project_id, :name)
  end

  def edit_params
    params.require(:team).permit(:team_size, :name, skill_ids: [])
  end
end

app/helpers/team_helper.rb
# frozen_string_literal: true

# Helper for team allocation
module TeamHelper
  def compability(target, teams, unassigned)
    if unassigned.id == target['team_id']
      best_team?(target, teams)
    else
      team = teams.where(id: target['team_id']).first
      team_compability(target, team, team.users).round(2).to_s
    end
  end

  def recompute(teams, unassigned_team, target_team, u_list)
    members = u_list[target_team.id.to_s]

    if unassigned_team == target_team
      members.map { |u| [u['id'], best_team?(u, teams, u_list)] }
    else
      users = User.find(members.pluck('id'))
      return if target_team.users == users

      users.map do |u|
        [u.id, team_compability(u, target_team, users).round(2).to_s]
      end
    end
  end

  def best_team?(target, teams, u_list = nil)
    user = u_list.blank? ? target : User.find(target['id'])
    return '' if user.empty_compability_data?

    results = compare_team(user, teams, u_list)

    best = results.max_by { |x| x[1] }
    best.blank? || best[1] <= 1.0 ? '' : "(#{best[1].round(2)}) Team #{best[0]}"
  end

  def compare_team(target, teams, u_list = nil)
    results = {}
    teams.each do |team|
      users = u_list.blank? ? team.users : User.find(u_list[team.id.to_s].pluck('id'))
      next if team.name == 'Unassigned' || users.size == team.team_size

      results[team.name] = team_compability(target, team, users)
    end
    results
  end

  def team_compability(target, team, users)
    user = target.is_a?(Hash) ? User.find(target['id']) : target

    1.0 * team_personality_score(user, users) *
      teamskill_score(team.skills, user.skills)
  end

  def member_compability(target, user)
    target.compatible_with?(user)
  end

  private

  def teamskill_score(t_skill, u_skill)
    return 1.0 unless t_skill.present? && u_skill.present?

    1.0 + ((t_skill.size - (t_skill - u_skill).size) / (t_skill.size * 10.0))
  end

  def team_personality_score(target, users)
    return 1.0 if target.personality.blank?

    user_score = 0
    counter = 0
    users.each do |usr|
      next if usr.personality.blank? || target == usr

      user_score += member_compability(target, usr)
      counter += 1.0
    end
    counter.zero? ? 1.0 : 1.0 + (user_score / (counter * 10.0))
  end
end

app/views/projects/teams/edit.haml
- content_for :title, 'Edit Team'

%section.section#teams
  .container.max-w-2xl
    %h1.title.is-4 Edit Team
    .box
      = form_with model: @team, url: [@project, @team], html: { '@ajax:error': 'ajaxError' } do |f|
        .field
          %label.label.required Team Name
          .control
            = f.text_field :name, class: 'input', required: true
        .field
          %label.label.required Max Team Size
          .control
            = f.number_field :team_size, min: 1, class: 'input', required: true
        .field
          %label.label Skills
          .select.is-multiple
            = f.select :skill_ids, @skills, {}, multiple: true
        .field.mt-8
          .control.flex.justify-between
            = f.submit 'Save', class: 'button is-success'
            = link_to 'Cancel', manage_project_teams_path(@team.project.id), class: 'button'

app/views/projects/teams/edit.html.haml
- content_for :title, 'Edit Team'

%section.section#teams
  .container.max-w-2xl
    %h1.title.is-4 Edit Team
    .box
      = form_with model: @team, url: [@project, @team], html: { '@ajax:error': 'ajaxError' } do |f|
        .field
          %label.label.required Team Name
          .control
            = f.text_field :name, class: 'input', required: ''
        .field
          %label.label.required Max Team Size
          .control
            = f.number_field :team_size, class: 'input'
        .field
          %label.label Skills
          .select.is-multiple
            = f.select :skill_ids, @skills, {}, multiple: true, include_blank: false
        .field.mt-8
          .control.flex.justify-between
            = f.submit 'Save Team', class: 'button is-success'
            = link_to 'Cancel', manage_project_teams_path(@team.project.id), class: 'button'

app/views/projects/teams/manage.haml
- content_for :title, @project.name

%section.section#projects
  .container
    .columns.is-vcentered
      .column
        %h1.title.is-4 Manage Teams
      .column
        - if user_signed_in? && (current_user == @project.user || current_user.admin?) && !@project.completed?
          .float-right.buttons.is-hidden-mobile
            = link_to new_project_team_path(project_id: @project.id), class: 'button is-primary' do
              %p New Team
              %span.icon
                %span.iconify{ 'data-icon': 'el:plus' }
            = link_to project_path(@project), class: 'button is-danger' do
              %p Back
          .buttons.is-hidden-tablet
            = link_to new_project_team_path(project_id: @project.id), class: 'button is-primary' do
              %p New Team
              %span.icon
                %span.iconify{ 'data-icon': 'el:plus' }
            = link_to project_path(@project), class: 'button is-danger' do
              %p Back
    .container
      %teams-manage{ ':project-id': @project.id, ':project-owner': @project.user.id }

app/views/projects/teams/new.haml
- content_for :title, 'Create a New Team'

%section.section#teams
  .container.max-w-2xl
    %h1.title.is-4 Create a new team
    %p.subtitle.is-6 Create teams to organise your members and diversify your skills.
    .box
      = form_with model: Team.new, url: [@project, Team.new], html: { '@ajax:error': 'ajaxError' } do |f|
        .field
          %label.label.required Team Name
          .control
            = f.text_field :name, class: 'input', required: ''
        .field
          %label.label.required Max Team Size
          .control
            = f.number_field :team_size, min: 1, class: 'input', required: ''
        .field
          %label.label Skills
          .select.is-multiple
            = f.select :skill_ids, @skills, { include_hidden: false }, multiple: true
        .field.mt-8
          .control.flex.justify-between
            = f.submit 'Create Team', class: 'button is-success'
            = link_to 'Cancel', project_path(@project), class: 'button'

app/views/projects/teams/new.html.haml
- content_for :title, 'Create Team'

%section.section#teams
  .container.max-w-2xl
    %h1.title.is-4 Create Team
    %p.subtitle.is-6 Create Teams to organise your members and diversify your skills.
    .box
      = form_with model: @team, url: [@project, @team], html: { '@ajax:error': 'ajaxError' } do |f|
        = f.hidden_field :project_id, value: @project.id
        .field
          %label.label.required Team Name
          .control
            = f.text_field :name, class: 'input', required: ''
        .field
          %label.label.required Max Team Size
          .control
            = f.number_field :team_size, class: 'input'
        .field
          %label.label Skills
          .select.is-multiple
            = f.select :skill_ids, @skills, {}, multiple: true, include_blank: false
        .field.mt-8
          .control.flex.justify-between
            = f.submit 'Create Team', class: 'button is-success'
            = link_to 'Cancel', project_path(@project), class: 'button'